services:
  jaeger:
    image: jaegertracing/all-in-one:latest@sha256:ab6f1a1f0fb49ea08bcd19f6b84f6081d0d44b364b6de148e1798eb5816bacac
    ports:
      - "16686:16686"
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:16686"]
      interval: 5s
      timeout: 5s
      retries: 10

  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    depends_on:
      jaeger:
        condition: service_healthy
