services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:16686"]
      interval: 5s
      timeout: 5s
      retries: 10

  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    environment:
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: jaeger
    configs:
      - source: grafana_custom_ini
        target: /etc/grafana/grafana.ini
    depends_on:
      jaeger:
        condition: service_healthy

configs:
  grafana_custom_ini:
    content: |
      [plugin.jaeger]
      as_external = true
